[project]
name = "mb-langgraph-v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.25.1",
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "google-genai>=1.50.0",
    "gradio>=6.2.0",
    "httpx>=0.28.1",
    "langchain>=1.0.2",
    "langchain-core>=1.0.1",
    "langchain-google-genai>=3.0.0",
    "langgraph>=1.0.1",
    "openpyxl>=3.1.5",
    "PyJWT>=2.10.1",
    "pytest>=9.0.1",
    "uvicorn>=0.35.0",
]
