from typing import List, TypedDict, Annotated
from langchain_core.messages import AnyMessage, AIMessage
from langgraph.managed.is_last_step import RemainingSteps

def add_message(existing_messages: list, new_messages: list) -> list:
    """
    Custom message handler with filtering for #FINISHED# tags
    This replaces LangGraph's default add_messages behavior
    """
    result_messages = existing_messages.copy()
    
    for msg in new_messages:
        # Filter für Interest Analyst: #FINISHED# Messages werden unsichtbar
        if hasattr(msg, 'content') and isinstance(msg.content, str):
            if "#finished#" in msg.content.lower():
                # Message mit leerem Content hinzufügen = unsichtbar für User
                filtered_msg = AIMessage(content="")
                result_messages.append(filtered_msg)
            else:
                # Normale Message hinzufügen
                result_messages.append(msg)
        else:
            # Message ohne content oder nicht-string content
            result_messages.append(msg)
    
    return result_messages

class AgentState(TypedDict):
    # The document provided
    userstreamingproviders: list[str]
    titles: List[str]
    #messages: Annotated[list[AnyMessage], add_messages]
    messages: Annotated[list[AnyMessage], add_message]
    movieinformation: str  # Information about the movie or TV shows that comes frrom tmdb 
    next_agent: str # Flag to indicate if the agent is ready for research
    #searchquery: str  # The search query generated by the interest analyst
    analystresult: str  # The result from the interest analyst, which may include questions or a summary of the user's interests
    # loaded_memory: Stores information loaded from the long-term memory store, 
    # typically user preferences or historical context.
   # loaded_memory: str
    
    # remaining_steps: Used by LangGraph to track the number of allowed steps 
    # to prevent infinite loops in cyclic graphs.
    remaining_steps: RemainingSteps