from typing import Optional, List, Annotated, Required
from typing import List, TypedDict, Annotated, Optional, Required
from langchain_core.messages import AnyMessage
from typing import List, TypedDict, Annotated, Optional, Required
from langgraph.graph.message import add_messages
from langgraph.managed.is_last_step import RemainingSteps 

class AgentState(TypedDict):
    # The document provided
    userstreamingproviders: list[str]
    titles: List[str]
    messages: Annotated[list[AnyMessage], add_messages]
    movieinformation: str  # Information about the movie or TV shows that comes frrom tmdb 
    next_agent: str # Flag to indicate if the agent is ready for research
    #searchquery: str  # The search query generated by the interest analyst
    analystresult: str  # The result from the interest analyst, which may include questions or a summary of the user's interests
    # loaded_memory: Stores information loaded from the long-term memory store, 
    # typically user preferences or historical context.
   # loaded_memory: str
    
    # remaining_steps: Used by LangGraph to track the number of allowed steps 
    # to prevent infinite loops in cyclic graphs.
    remaining_steps: RemainingSteps